#for testing whether we can train on high h2 genes from random weights if i increase learning rate, allow more patience and more epochs. Using a shorter sequence to speed things up
seq_length: 49152
learning_rate: 5e-4
train_batch_size: 8
num_individuals_per_gene: 128
alpha: 0.5
experiment_name: "test_random_weights_higher_lr_full_patience"
max_epochs: 750
precision: bf16-mixed
tissues_to_train: "Whole Blood"
gradient_clip_val: 0.05
seed: 0
patience: 750
valid_metrics_save_freq: 2
train_gene_dir: /pollard/data/projects/sdrusinsky/enformer_fine_tuning/data/genes/Whole_Blood/high_h2_sg_revisions
valid_gene_path: /pollard/data/projects/sdrusinsky/enformer_fine_tuning/data/genes/empty.txt
test_gene_path: /pollard/data/projects/sdrusinsky/enformer_fine_tuning/data/genes/empty.txt